# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginandreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default='profileimage/default-profile-picture.jpeg', upload_to='profileimage'),
        ),
    ]
