# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginandreg', '0004_auto_20170228_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
