# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
