# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20170227_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(max_length=45, null=True, upload_to=b''),
        ),
    ]
