# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20170228_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255)),
                ('genre', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('tags', models.CharField(max_length=45)),
                ('image', models.FileField(null=True, upload_to='documents/')),
                ('song', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
