# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20170228_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.FileField(null=True, upload_to='/static/upload/images'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='/static/upload/songs'),
        ),
    ]
