# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20170228_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
