# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20170302_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='song_playlists', to='upload.Song'),
        ),
    ]
