# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundcloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_song', to='upload.Song'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to='loginandreg.User'),
        ),
    ]
